```python
import openai
from config.settings import API_KEY

def generate_response(prompt):
    """
    Generates a response from OpenAI based on the given prompt.

    :param prompt: A clear and concise prompt for the OpenAI model.
    :return: A detailed and helpful response generated by OpenAI.
    """
    openai.api_key = API_KEY

    try:
        response = openai.Completion.create(
            model="gpt-4-turbo",
            prompt=prompt,
            max_tokens=150
        )
        return response.choices[0].text.strip()
    except openai.error.OpenAIError as e:
        raise Exception(f"An error occurred while generating a response from OpenAI: {e}")
```