version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/code
      - ./data:/code/data
    environment:
      - OPENAI_API_KEY=${API_KEY}
    ports:
      - "5000:5000"
    command: python -m api.app

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/frontend:/code/frontend
    ports:
      - "80:80"

  worker:
    build: .
    volumes:
      - .:/code
      - ./data:/code/data
    environment:
      - OPENAI_API_KEY=${API_KEY}
    command: celery -A tasks worker --loglevel=info

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:13"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=codeanalysis
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=codeanalysisdb
    ports:
      - "5432:5432"

volumes:
  postgres_data: